-- MySQL Script generated by MySQL Workbench
-- Wed Apr  2 19:31:12 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema famfinan
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema famfinan
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `famfinan` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
-- -----------------------------------------------------
-- Schema formulario
-- -----------------------------------------------------
USE `famfinan` ;

-- -----------------------------------------------------
-- Table `famfinan`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `famfinan`.`categoria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `famfinan`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `famfinan`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_completo` VARCHAR(250) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `dat_nasc` DATE NOT NULL,
  `grupo_familiar` VARCHAR(30) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `login` VARCHAR(30) NOT NULL,
  `senha` VARCHAR(30) NULL DEFAULT NULL,
  `nivel_acesso` VARCHAR(10) NULL DEFAULT 'usuario',
  PRIMARY KEY (`id`))
ENGINE = MyISAM
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `famfinan`.`despesas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `famfinan`.`despesas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `categoria` VARCHAR(50) NULL DEFAULT NULL,
  `descricao` VARCHAR(50) NULL DEFAULT NULL,
  `valor` DOUBLE NULL DEFAULT NULL,
  `dataVenc` DATE NULL DEFAULT NULL,
  `pago` VARCHAR(10) NOT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id`, `id_usuario`),
  INDEX `fk_despesas_usuario1_idx` (`id_usuario` ASC) VISIBLE)
ENGINE = MyISAM
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `famfinan`.`gruposfamiliar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `famfinan`.`gruposfamiliar` (
  `id_grupo_familiar` INT NOT NULL AUTO_INCREMENT,
  `administrador` VARCHAR(100) NULL DEFAULT NULL,
  `nome` VARCHAR(100) NULL DEFAULT NULL,
  `percentual` DOUBLE NULL DEFAULT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`, `usuario_id`),
  UNIQUE INDEX `administrador` (`administrador` ASC) VISIBLE,
  INDEX `fk_gruposfamiliar_usuario_idx` (`usuario_id` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `famfinan`.`receitas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `famfinan`.`receitas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `valor` DECIMAL(10,2) NULL DEFAULT NULL,
  `categoria` VARCHAR(30) NULL DEFAULT NULL,
  `data_registro` VARCHAR(50) NULL DEFAULT NULL,
  `numParcelas` INT NOT NULL,
  `pago` VARCHAR(10) NOT NULL,
  `id_usuario` INT NOT NULL,
   PRIMARY KEY (`id`, `id_usuario`),
  INDEX `fk_receitas_usuario1_idx` (`id_usuario` ASC) VISIBLE)
ENGINE = MyISAM
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `famfinan`.`despesas_has_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `famfinan`.`despesas_has_categoria` (
  `despesas_id` INT NOT NULL,
  `categoria_id` INT NOT NULL,
  PRIMARY KEY (`despesas_id`, `categoria_id`),
  INDEX `fk_despesas_has_categoria_categoria1_idx` (`categoria_id` ASC) VISIBLE,
  INDEX `fk_despesas_has_categoria_despesas1_idx` (`despesas_id` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `famfinan`.`receitas_has_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `famfinan`.`receitas_has_categoria` (
  `receitas_id` INT NOT NULL,
  `categoria_id` INT NOT NULL,
  PRIMARY KEY (`receitas_id`, `categoria_id`),
  INDEX `fk_receitas_has_categoria_categoria1_idx` (`categoria_id` ASC) VISIBLE,
  INDEX `fk_receitas_has_categoria_receitas1_idx` (`receitas_id` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
